### ISSUE TITLE
Linting errors...

### ISSUE THREAD

**Issue by Limpan** [teknik-eksjo/chronos#109]
Issue #106 resulted in linting errors.

**Comment by Greenheart** [comment]
This will be fixed in the upcoming commits. Szymon simply shared his WIP to allow me to continue on it.

**Comment by Limpan** [comment]
That's a bad way to share code, @Catagen. It would have been better to push to your fork so that @Greenheart could have pulled directly from there.

Pushing half-broken half-finished work-in-progress code into our main development branch is asking for grumpy collaborators...

**Comment by Greenheart** [comment]
@Limpan I think we all know this was a bad idea. Szymon were in a hurry and I didn't pay attention to how the changes were shared until they already were in the PR and Szymon had to leave.

We'll fix this in the commits coming in the next few days.
