### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by hugolundin** [teknik-eksjo/chronos#15]
What permission levels should exist?

**Comment by hugolundin** [comment]
|  | WRITE_SCHED. | READ_SCHED. | APPROVE_SCHED. | UNLOCK_SCHED. | CREATE_USER |
| --- | --- | --- | --- | --- | --- |
| Teacher | x |  |  |  |  |
| Principal |  | x | x | x |  |
| Admin |  | x |  | x | x |
| Super Admin | x | x | x | x | x |

**Comment by Greenheart** [comment]
What's the unlock schedule level for?

Apart from that this looks good!

**Comment by Limpan** [comment]
When the principal approves a schedule it is locked for further editing but there might be a need to change it. Since only the principal should be able to approve but principals and admins should be able to open up the schedule for further editing.

**Comment by Greenheart** [comment]
That sounds good!
