### ISSUE TITLE
Create routes for the main app views

### ISSUE THREAD

**Issue by Greenheart** [teknik-eksjo/chronos#16]
Should we build the application with a different route for each view?

In that case, we could use `window.location = "http://www.app.com/next-route"` to redirect the user to the next route from the client and I guess a HTTP`POST`-handler could do a redirect from the server if we only want it to happen when the user's data is saved in the database.

The following routes should be added to `views.py` or `forms.py`:
- [ ] /login (might just be the `'/'`-route?)
- [ ] /instructions
- [ ] /base-schedule (naming?)
- [ ] /deviations (naming?)
- [ ] /summary

**Comment by Limpan** [comment]
I'd advise against building the application as a single page application, at least at first.
