### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by Greenheart** [teknik-eksjo/chronos#17]
We will need some kind of admin UI where principals and administrators can access the user's schedules.

To allow admins to get a overview of an user, we might be able to reuse the `summary`-template from the teachers' view and just add a few buttons to allow admins to modify/ approve the schedule?

**Comment by hugolundin** [comment]
Authentication model is now finished. Continuing with administrator UI.

**Comment by Greenheart** [comment]
This is too general so I'm closing it now. Let's discuss this in several smaller issues instead
