### ISSUE TITLE
Login routes

### ISSUE THREAD

**Issue by hugolundin** [teknik-eksjo/chronos#20]
I have some thoughts about how the routes for authentication should be structured. 
Right now, the blueprint for auth goes after **/auth**.

My thoughts is about how the routing should be for signing in, and explain for teachers who tries to sign in without using the link, how they should do in the following way: 

If you go to **/**, and are not signed in, you should be redirected to **/auth**, which provides something like this:
![1](https://cloud.githubusercontent.com/assets/9110669/14365677/3a73ee9c-fd0f-11e5-9d5f-223a1497be92.png)

If you press "Administrator", you are redirected to **/auth/admin** which provides a sign in-page for the administrator. If you press "Teacher", you are redirected to **/auth/teacher** (or another url not decided yet), you are provided with something like this:
![2](https://cloud.githubusercontent.com/assets/9110669/14365791/d4d4657a-fd0f-11e5-9b77-1041d4efd890.png)
(If "click here" is clicked, the user is provided a page with an email form and a reset button). 

What are your thoughts on this?

**Comment by Limpan** [comment]
You're overthinking the matter. How would you get to /admin as a regular teacher? Why wouldn't you understand that you're doing something special?

I think / should contain a simple landing page that tells you that you need to follow the link in the email. Like your example.

Don't ruin the user experience for the admin users that are supposed to use username and password.

**Comment by hugolundin** [comment]
I agree that I was overthinking the issue yesterday. But if we think about the urls for administration authentic, should the sign in page go under /Auth or /Auth/admin?

**Comment by Limpan** [comment]
Use /auth/login and /auth/logout and with automatic redirection you can have /admin. If not authenticated you will be redirected to /auth/login and then back after successful login. That way you can use the route /admin for dold kind of dashboard.
