### ISSUE TITLE
Implement the slider component

### ISSUE THREAD

**Issue by Greenheart** [teknik-eksjo/chronos#23]
I see three alternatives at the moment:
## 1. Use jQuery UI Slider

Almost the functionality we need but bad documentation.
## 2. Custom built solution

Maybe using handle-`div`s positioned in a "slider-container" and `ondrag` / `ondrop` events
## 3. Modify and extend some library or code-snippet

For example [this article looks promising](http://thenewcode.com/757/Playing-With-The-HTML5-range-Slider-Input) or [this snippet](http://stackoverflow.com/a/31083391/4183985)

---
## Progress
- [X] Make time range work with minutes
- [X] Fix ticks for time ranges
- [X] Clean up the old code
- [x] Comment ticks code
- [x] Remove slider controllers (add, remove, select type)
- [x] Change the label names
- [x] Test behaviors --> eg. Should not be possible to work longer than 5 hours
- [x] Fix css styling
- [x] Change color slider to red on error
- [ ] Fix handle types --> Use work, lunch, leisure
- [x] Translate the slider stylesheet into SASS

**Comment by erikcollerstedt** [comment]
This might be a good solution?

[http://embed.plnkr.co/XJyMrxVgFixCKkUnwUTA/preview](http://embed.plnkr.co/XJyMrxVgFixCKkUnwUTA/preview)

**Comment by Limpan** [comment]
@erikcollerstedt It looks very promising!

**Comment by shhmon** [comment]
I think we should translate the whole slider stylesheet into SASS for consistency. I'll add that as a checkbox. Also, if you're editing the styles please follow the current pattern and avoid using simplistic non-reusable stylings, that would just create a mess.
