### ISSUE TITLE
Write down some requirements, plan the workflow and decide which milestones we aim to achieve

### ISSUE THREAD

**Issue by Greenheart** [teknik-eksjo/chronos#3]
Before we start coding, let's write down a basic outline of **how** we plan to work on this project and **what** we're trying to achieve.

A good place to store the information might be in a GH-wiki for this repository alternatively keep it in some documentation in Sphinx.
1. Gather requirements for the app
2. Discuss how we are going to document the development process and the resulting application.
   - GitHub Wiki
   - Google Docs
   - External markdown-files in the repository in a `docs/`-folder
   - Keep as many discussions as possible about the project documented in GitHub-issues and PR:s. A searchable alternative where the design-decisions are put in context together with the actual changes to the code and available for future maintainers. (I think this is the best alternative)
3. Discuss the workflow
   - Make use of GitHub issues, tag them with labels and assign them to yourself whenever you work on something
   - Use personal forks and branches with the naming `fix/yyyyyyyyy` or `feature/yyyyyyyyyyyy`
   - Use branches in the main repo
     - `master` for releases
     - `develop` for in-progress fixes and features
4. Create the app structure and decide what technology stack we're going to use.
5. Start solving the problemzzz

**Comment by Limpan** [comment]
> External markdown-files in the repository in a docs/-folder

Basically means to use Sphinx. Using Sphinx there will be a lot of possibilities. Referencing code is simple, and you can also structure the documentation freely.

I think you should use GH for documenting the _process_ and Sphinx (with readthedocs.org) to document the _product_.

**Comment by Limpan** [comment]
Note that github wikis are available as repositories (and are basically a bunch of text files).
https://help.github.com/articles/adding-and-editing-wiki-pages-locally/
