### ISSUE TITLE
Create API blueprint or not

### ISSUE THREAD

**Issue by hugolundin** [teknik-eksjo/chronos#32]
I need a route which returns a json-object. What do you think is the best, place it in a API-blueprint or define a route which returns json on the admin blueprint? @limpan

**Comment by Limpan** [comment]
Start out with IT as a route in admin. If it is needed from outside of admin and there is more routes like it (in other blueprints and/or accessed from outside of the blueprint), consider moving them to an internal API blueprint.

If you have lots of routes in admin that only return json, put them in a separate file, for instance api.py and import it like views.py in the blueprints init file.
