### ISSUE TITLE
Organize features in milestones for each stage of the project

### ISSUE THREAD

**Issue by Greenheart** [teknik-eksjo/chronos#34]
![Possible Features](http://i.imgur.com/wMkAXDM.jpg)

Which of these features do we want to add and where?

**Comment by Limpan** [comment]
Did I miss anything?
@hugolundin, @erikcollerstedt, @Catagen, @Greenheart, @Kallshem

**Comment by Greenheart** [comment]
@teknik-eksjo/te13 Should we rename the milestones?

Milestone 0 --> Beta
Milestone 1 --> 1.0

Future can stay the same, it's a good name

**Comment by Greenheart** [comment]
@teknik-eksjo/te13 I updated the names of the milestones. Let's discuss it tomorrow!
