### ISSUE TITLE
Who should review pull requests?

### ISSUE THREAD

**Issue by hugolundin** [teknik-eksjo/chronos#5]
I realized that we really did not decide who that should review our pull requests to the repository. Me and Szymon talked about it and thought about a standard code-review process, where everyone are able to merge pull requests, but someone else should have reviewed the code before merge.

**Comment by Limpan** [comment]
It would be useful with Travis and some automated tests. Some linting, unit tests and maybe even selenium tests.

**Comment by hugolundin** [comment]
Of course. But I rather thought about your recent pull request (#4). Who should be responsible for merging it?

**Comment by Limpan** [comment]
Of course @hugolundin, I just wanted to point out that there's good tools that should be used in the process.

I see two alternatives.
1. One project maintainer that manages merging of pull requests. A bit rigid but allows for greater control.
2. Anyone is allowed to merge pull requests after someone reviewed the code. Leaner alternative. Greater potential for all to learn about the merging process.

Both alternatives should require that all tests have passed.

**Comment by Greenheart** [comment]
Alternative two will allow us to learn more.
