### ISSUE TITLE
Add a button to delete a user from the admin's overview of users

### ISSUE THREAD

**Issue by Greenheart** [teknik-eksjo/chronos#54]
## Description

After discussing this with @hugolundin this is what we have come up with

Clicking the delete-button should **prompt the user to confirm** that they really want to delete the user from the system. **Maybe even prompt for the admin password** since this process won't happen that often and since a mistake/abuse here could make huge damage to the user losing their data.

[Event-handling for buttons in a Flask-app](http://stackoverflow.com/questions/29933655/multiple-buttons-on-a-flask-webapp) - Might be a good starting point on how to implement the actual data transfer and verification popup in the message.

Take inspiration from the invitation-system in [Blaze Penguinz](https://github.com/Greenheart/blaze-penguinz) - It implemented the popup-system we want and could pretty easily be modified + restyled to fit our usecase better

---
## Features to implement
- [x] Prompt the admin to confirm (maybe even verify with their password)
- [x] Send a request to the backend using some JS (check out the link to SO above ↑↑↑↑↑)
- [x] Backend auth to check if user is signed in
- [x] Backend process the request
- [x] The backend responds with a result, which is displayed in the client (Popup / Bootstrap notification on top of screen)

**Comment by hugolundin** [comment]
@limpan and I discussed that a password prompt may be overkill if we only flag the user as inactive instead of deleting it totally from the database, and then clean up users after a while or manually, to easier be able to restore missclicks

**Comment by hugolundin** [comment]
*either automatically or manually

**Comment by Greenheart** [comment]
And then in that case require the admin's password when cleaning the
deactivated users? What I want I protect from is **a malicious user who
passes by an unguarded computer logged in as admin and starts making
serious damage.**

**Comment by Greenheart** [comment]
Another feature GitHub offers is the ability to edit posts by clicking he
pen in upper right corner... ;)

**Comment by hugolundin** [comment]
There is no pen on mobile ☹️

**Comment by Greenheart** [comment]
Then just open the devtools, edit the source to link to the image, write
some JS and finally add some nice inline-styling and you're done! ^^

**Comment by hugolundin** [comment]
@Limpan @Greenheart I am almost done with the delete-button (some linting and refactoring left), but we need to decide if it should remove the user permanently or set a inactive flag on the user. What are your thoughts on this?

**Comment by Greenheart** [comment]
@hugolundin Good job!

I'd say flag as inactive, but don't delete completely from DB. Like you said above

> flag the user as inactive instead of deleting it totally from the database, and then clean up users after a while or manually, to easier be able to restore missclicks

**Comment by Limpan** [comment]
I agree. Mark as inactive and then possibly a cleanup action in the future.

**Comment by Greenheart** [comment]
> possibly a cleanup action in the future.

This would be something for `Milestone 1` or even `Future`
