### ISSUE TITLE
Stop column widths in the /admin/users table from resizing upon search

### ISSUE THREAD

**Issue by Greenheart** [teknik-eksjo/chronos#55]
Look at the column header widths

[GIF showing the issue](https://giphy.com/gifs/xT1XGxqokJoVfps1c4)

Could this possibly be solved with some custom css that overrides the default bootstrap-table behavior?

**Comment by Limpan** [comment]
Quick fix is probably to add some inline styling, for example `style="width: 20%"` (for the header cells).

**Comment by Greenheart** [comment]
@Limpan We tried the quick fix but it will only cause more problems further on and is thus no good idea.

## Possible solutions
- Will there be some kind of max-lengths for fields in the User-table that we could adapt columns to?
- Dynamic widths based on the widest content in each column

**Comment by shhmon** [comment]
I'm on it as soon as the current admin UI version is pushed to this repo
