### ISSUE TITLE
Script for database population

### ISSUE THREAD

**Issue by Limpan** [teknik-eksjo/chronos#83]
Write a script that generates some bogus data. Primarily for manual testing.

**Comment by Greenheart** [comment]
It would be good if this script added user accounts with different permission-levels.
- 1-2 Principals
- 1-2 Admins
- 5-10 Teachers

**Comment by Greenheart** [comment]
@erikcollerstedt Feature request for this script:
- Create an admin-account based on information in the environment variables set from the `.env`-file

This would for allow for a simple re-creation of the personal admin-account just by keeping a `.env`-file updated.

---

## To implement this:
1. Add the following rows to `.env` and enter data for your personal admin-acc:
   - `CHRONOS_ADMIN_FIRST_NAME=Samuel`
   - `CHRONOS_ADMIN_LAST_NAME=Plumppu`
   - `CHRONOS_ADMIN_PASSWORD=supersecret`
2. Access `.env`-variables through `os.environ.get(<VAR_NAME>)`
3. create new `User` with data from `.env`
4. `db.session.add(<new_user>)`
5. `db.session.commit()` --> **Which we already do in the end of the script**

**Comment by Limpan** [comment]
I find the name of the admin user pretty irrelevant since we do our logins with the email. I actually think that it's more fun to be surprised with a new, possibly, funny name!

A genuinely useful suggestion from me: Write all user emails and passwords to a file in the `tmp` folder we already use for tests.

**Comment by Greenheart** [comment]
> I find the name of the admin user pretty irrelevant since we do our logins with the email. I actually think that it's more fun to be surprised with a new, possibly, funny name!

Haha yeah that's true!

> Write all user emails and passwords to a file in the tmp folder we already use for tests.

I've still not seen this mystic `/tmp`-folder :yum:

**Comment by Limpan** [comment]
The HTML report for test coverage uses it.

**Comment by Greenheart** [comment]
How do i get that html-report? `./manage.py test --coverage`? or some flag for html?

**Comment by hugolundin** [comment]
> How do i get that html-report? ./manage.py test --coverage? or some flag for html?

That should be it.

**Comment by Greenheart** [comment]
Strange because that command only creates the file .coverage but nothing
else.

**Comment by hugolundin** [comment]
> Strange because that command only creates the file .coverage but nothing
> else.

Have you tried `./manage.py test --coverage html`?
I am not at home right now, but if @Limpan does not respond before, I can check later.

**Comment by erikcollerstedt** [comment]
Pull request #98 adds users and teachers. 
We still need to add a side script for work periods, schedules and principals.

**Comment by Greenheart** [comment]
The `./manage.py seed`-script could be updated to
- [x] add 2-3 `WorkPeriod`s
- [x] add some `Schedule`s to each `WorkPeriod`
  - with the `user_id`-field set to the `User.id` of the Schedule's owner (one of the bogus-users in this case)
  - with the `work_period_id` set to the `WorkPeriod.id` this schedule relates to
- [x] add some `Deviations` to each `Schedule`
- [x] add a `BaseSchedule` to each `Schedule`
- [x] Additionally, each `BaseSchedule` need several `WorkDays`

**Comment by Greenheart** [comment]
Almost done with adding `WorkPeriod`s according to my previous comment. Just need to generate random dates for the `Deviation`s that's in the range of the current work_period.

**Comment by Greenheart** [comment]
PR #112 adds almost all functionality we want at the moment. Some future improvements are mentioned in the PR-description but I think they would could be discussed and solved in more specific issues in the future.

@erikcollerstedt There's just one thing missing before we can close this now -  the script need to add `Principal`s and maybe another admin that isn't `CHRONOS_ADMIN`.

---

## Before this issue can be closed, the script should be able to insert
- [x] 1-2 `Principal`s - I think 2 is good because then we can test how different `Principal`s co-exist and collaborate in the app.
- [x] 1-2 normal `Admin`s without the super-admin privileges - to test how normal admins will use the app.
