### ISSUE TITLE
Add information about recommended linters and styleguide to Contributing Guidelines

### ISSUE THREAD

**Issue by Greenheart** [teknik-eksjo/chronos#85]
By adding live-linting to our editors, we'll get better code consistency and catch syntax-mistakes more easily.

I suggest [linter-js-standard](https://atom.io/packages/linter-js-standard) as the JS-linter for Atom.

There are [several Python linters for Atom](https://atom.io/packages/search?q=linter-python) - **Which one should we use?**

**Comment by hugolundin** [comment]
I think that tools is a rather personal preference, and that we should not waste time on writing tool recommendations in our contribution guide. Although, some more about linting and code consistency would be beneficial to add.

**Comment by Greenheart** [comment]
> I think that tools is a rather personal preference, and that we should not waste time on writing tool recommendations in our contribution guide.

Good point.

> some more about linting and code consistency would be beneficial to add. 

So we should decide upon what styleguides to follow but allow everyone to pick their own compatible tools?

**Comment by hugolundin** [comment]
Sounds good to me, what do the rest of @teknik-eksjo/te13 think?

**Comment by Greenheart** [comment]
3 minutes without a response omg :octocat:

**Comment by Limpan** [comment]
I think it's sufficient that we have linting in our manage.py-script.

I'll do some searching for a good linting solution for js, sass, html and whatnot.
